const{test,expect}=require('@playwright/test')
//add faker library to handle dialog assertion
const {faker}=require('@faker-js/faker');
//generate random name using faker library
const randomName=faker.person.fullName();
//console.log("Random name generated by faker library:",randomName);
//enter tc name
test('Handle frame test case',async({page})=>{
    await page.goto('https://demo.automationtesting.in/Frames.html');

    
    //check how many frame in web page first frame
    const allframe=await page.frames();
    //print total frames in web page
    console.log("Total frames in web page:",allframe.length);
    //1 st approch to handle frame object there are 2 ways to handle frame 1st by using name or id and 2nd by using url
    //switch to first frame by using frame object by name or id
    const frame1=page.frame({name:'SingleFrame'});
    //enter the text in first frame
    await frame1.locator("input[type='text']").fill('Welcome to Playwright');
    //takw screenshot of first frame
    await page.screenshot({path:`D:\\Swamini\\Playwright\\screenshot\\${randomName}.png`});
    //switch back to main page
    //await page.mainFrame();
     //click on 2nd frame button using role locator
    //await page.getByRole('link', { name: 'Iframe with in an Iframe' }).click();
    //click on 2nd frame button using xpath //a[contains(text(),'Iframe with in an Iframe')]
    await page.locator("//a[contains(text(),'Iframe with in an Iframe')]").click();
    await page.screenshot({path:`D:\\Swamini\\Playwright\\screenshot\\${randomName}.png`});
    //switch to 2nd frame by using frame object by frame locator
const frame2=page.frame({url:'https://demo.automationtesting.in/SingleFrame.html'});
await page.screenshot({path:`D:\\Swamini\\Playwright\\screenshot\\${randomName}.png`});
    //enter the text in 2nd frame
    console.log("Switching to second frame and entering text...",+frame2);

});